# TargetSelector 플러그인을 위한 고급 설정 파일
# 이 설정들 중 일부는 안전하지만, 또 다른 것들은 잘못 수정했을 경우 서버에 오류가 발생할 수 있습니다
# 새로운 설정/기본은 이 파일을 업그레이드할 때 자동으로 나타나지 않습니다

permission:
  #대상 선택자의 권한
  #원하는대로 수정할 수 있습니다
  player: "true"
  random: "true"
  all: "op"